caption: train.caption.tsv
caption_coco_format: train.caption_coco_format.json
#caption_linelist: train.caption.linelist.tsv
img: visual_features_tsv/train_segmented_features.tsv
label: train.label.tsv