DATASETS:
  TRAIN: ("MAD_train",)
  VAL: ("MAD_val",) 
  TEST: ("MAD_test",)

MODEL:
  VLG:
    NUM_CLIPS: 64
    NEG_PROB: 0.7
    FEATPOOL:
      INPUT_SIZE: 512
      HIDDEN_SIZE: 512 
      KERNEL_SIZE: 1 
      DROPOUT: 0.0
      POS: 'none' 
      GROUPS: 32
      WIDTH_GROUP: 4
      NUM_AGGREGATOR_LAYERS: 7
      NUM_NEIGHBOURS: 7

INPUT:
  STRIDE: 1
  LANG_FEAT: clip
  NUM_PRE_CLIPS:   128 
  PRE_QUERY_SIZE:  512  # 300 for glove and 512 for clip
  IMG_RES: 224  #this is the default that was set for MAD visual features extraction

DATALOADER:
  NUM_WORKERS: 0 

OUTPUT_DIR: output/model


# FAVD args
img_res: 224
vidswin_size: "base"
kinetics: 600
pretrained_2d: 0